### ISSUE TITLE
ENH: python 3

### ISSUE THREAD

**Issue by CJ-Wright** [diffpy/diffpy.srfit#20]
Would it be possible to update this to be python 3 happy?
[This library might be of help](https://docs.python.org/2/library/2to3.html)

**Comment by pavoljuhas** [comment]
Yes, that is the plan.  We'll need to convert the full stack of dependencies - diffpy.Structure, pyobjcryst, diffpy.srreal to get the full functionality in PY3.  SrFit can still function without those as a bare-bones fit manager.

I will create a python3 branch to work on conversion there.  Can you help with code reviews?

**Comment by CJ-Wright** [comment]
I'd be happy to help!

**Comment by pavoljuhas** [comment]
I think it is better to first complete a minor release with #18, #19 wrapped up.  We can branch off python3 then.

**Comment by CJ-Wright** [comment]
Sure!

**Comment by CJ-Wright** [comment]
Has there been any progress on this front?

**Comment by pavoljuhas** [comment]
python3 branch passes unit tests with bare srfit as of a00924f4a83eb1f05604f113a5ff46ae3110144f.

Closing in lieu of https://github.com/orgs/diffpy/projects/1.
