### ISSUE TITLE
CI: why does the CI test with the system python?

### ISSUE THREAD

**Issue by CJ-Wright** [diffpy/diffpy.srfit#28]

**Comment by pavoljuhas** [comment]
To check if srfit works with system Python 2.7 on Ubuntu 12.

**Comment by CJ-Wright** [comment]
Is that really needed? Personally I would strongly discourage installing anything onto the system python. Also is the current conda python 2.7 that different?

**Comment by pavoljuhas** [comment]
Users can install to USER_SITE leaving the system Python alone.  The source-distribution of
diffpy-cmi utilizes system Python so this makes sure cmi keeps working if users choose [to update their installation](https://github.com/diffpy/diffpy-release/blob/v2.0/diffpy-cmi/README.txt#L80).  In addition, the system-python CI variant installs from sources tarball and thus checks its integrity.
