### ISSUE TITLE
fix whitespace and DOS file format in data files

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.srfit#39]
And make sure SAS data are in sync with srfit-sasview.

**Comment by sbillinge** [comment]
@pavoljuhas do you need help with this one?

**Comment by pavoljuhas** [comment]
> do you need help with this one?

No, thank you.  It is a 5 minute task, but not essential, so I leave it for after the 3.0alpha release.
I just put it here as a reminder.

I could use some help with other issues - will send you an email on those.
