### ISSUE TITLE
Same observation but different ways of setting observations lead to different refinement

### ISSUE THREAD

**Issue by chiahaoliu** [diffpy/diffpy.srfit#40]
I was doing some tests on my use case : 

````
Assign np.array to FitRecipe instances in order to create different recipes dynamically
````
and I found different read-in methods would lead to different refinement results, even for the same Gr file.
Here is my test:

0. assume I have experimental observation with filename ``obs_fn``.

1. create an ``FitRecipe`` instance using
   ````
   PDFContribution.loadData(obs_fn)
   ````
   to pass ``xobs`` and ``yobs`` to that recipe, defined as ``fit_loadData``.

2. create another ``FitRecipe`` instance using
   ````
   xobs, yobs = np.loadtxt(obs_fn)
   PDFContribution.Profile.setObservedProfile(x, y)
   ````
   to pass ``xobs`` and ``yobs`` to that recipe, defined as ``fit_setObs``.

3. run refinements with the same ``spicy.opmize.minpack.leastsq`` engine on both ``fit_loadData`` and ``fit_setObs``.

4. refinement from ``fit_loadData`` yields better rw value (1%) and different refined values as well. Here is the brief summary:
````
INFO: with method np.loadtxt
final param val = [ 3.52346061  0.00635548  0.41412223  0.81828005  0.04027503  0.007821  ]
rw = 0.029218
INFO: with method diffpy.srfit.pdf.pdfcontribution.loadData
final param val = [ 3.52346061  0.00635548  0.41273426  0.84593323  0.04029146  0.00690975]
rw = 0.019323
````

A temporary repo has been created to include files that can reproduce this error
https://github.com/chiahaoliu/srfit_test
Executing ``loadGr_comprare.py`` should be able to see the result summarized above.

My reasoning for why these two methods should be equivalent comes from that ``loadData`` eventually calls ``setObservedProfile`` as shown [in the code](https://github.com/diffpy/diffpy.srfit/blob/master/src/diffpy/srfit/fitbase/profile.py#L111) and ``np.loadtext`` should yield fairly accurate result. 

Is there any reason for this discrepancy?  Thanks.

**Comment by pavoljuhas** [comment]
> `PDFContribution.loadData(obs_fn)`

This reads the `qmax` value from the `obs_fn` file and sets it for PDFGenerator-s associated with that contribution.  You can check what metadata were loaded and are active with

```python
pdfcontrib.profile.meta
pdfcontrib.nickel.meta
```

You should get the same fit if in the array-data case you'd do

```python
pdfcontrib.setQmax(value)
pdfcontrib.setQmin(value)
```

**Comment by chiahaoliu** [comment]
Yes, ``setQmin`` and ``setQmax`` does help create exact the same the result as ``loadData``.

Thanks for the reply ! Close this issue for now.
