### ISSUE TITLE
PDFContribution takes in loaded data

### ISSUE THREAD

**Issue by CJ-Wright** [diffpy/diffpy.srfit#41]
What kind of data does the `PDFContribution` object need for loadData? Would it be possible to have a method that takes in in python base types + numpy arrays?

**Comment by pavoljuhas** [comment]
It reads a text data file with a 2 to 4-column data block for *r*, *Gobs*, *dr*, *dGobs*.  Any lines formatted as `qmax=X`, `qdamp=Y`, etc., are applied as PDFContribution metadata.

You can pass numpy arrays or lists of floats directly using

```python
pdfcntb.profile.setObservedProfile(xobs, yobs, dyobs=None)
```

PS: please close if this answers your question.
